### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by afangg** [Brelliothe/PADM-Final-Project#1]
Please make the videos easier to view. Right now I have to download them to watch them. Put them in the README, put it in Google Drive and paste the link, or find an alternative. Thanks

**Comment by Brelliothe** [comment]
Updated, please check it! Thank you.

发件人: Alisha ***@***.***>
发送时间: 2022年12月14日 10:03
收件人: ***@***.***>
抄送: ***@***.***>
主题: [Brelliothe/PADM-Final-Project] Videos (Issue #1)


Please make the videos easier to view. Right now I have to download them to watch them. Put them in the README, put it in Google Drive and paste the link, or find an alternative. Thanks

―
